# Generated by Django 2.2.1 on 2019-05-12 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='genger',
            new_name='gender',
        ),
    ]
